Pin by (grand)child PID
mitre/gameboard pull request #21
Opened 2021-01-05 20:11 UTC by garunagiri

Feature to pin blue abilities by entering the child or grandchild process' PID.
Dependent on the following Response plugin PR: https://github.com/mitre/response/pull/63

2021-03-01 20:35 UTC, protoli approved these changes

2021-03-04 22:52 UTC, unkempthenry approved these changes

2021-03-08 05:07 UTC, clenk requested changes
It looks like there's a lot of CSS embedded in the HTML, including on elements that have an id. Is there any more stylings you can move to the CSS file instead of the HTML?

2021-03-08 05:07 UTC, clenk commented on app/gameboard_api.py
> +                return web.json_response(dict(message='Pinned to parent PID: ' + str(matches[0]), multiple_links=False))
I think in CALDERA using the string `.format()` method is preferred over concatenating with `+`. You could also use `link.pin` instead of `matches[0]`, which I think would be more readable.

2021-03-08 05:07 UTC, clenk commented on app/gameboard_api.py
> +            return web.json_response(dict(message='Pinned to PID: ' + str(data['updated_pin']), multiple_links=False))
Same thing here with using `.format()` and `link.pin`.

2021-03-08 05:07 UTC, clenk commented on app/gameboard_api.py
> +        return None
This feels like a method more widely-useful than just in gameboard. Maybe a future PR should move it to the Link class?
On a second look though, it doesn't look like it's actually used anywhere.

2021-03-08 05:07 UTC, clenk commented on static/js/gameboard.js
> +            for (let i=0; i<links.length;i++) {
```suggestion
            for (let i=0; i<links.length; i++) {
```

2021-03-08 05:07 UTC, clenk commented on static/js/gameboard.js
> +    function updatedPin(data) {
I'm not sure `updatedPin()` needs to be nested in `savePin()` - might make `savePin()` more readable to pull it up out of `savePin`.

2021-03-08 16:00 UTC, garunagiri commented on app/gameboard_api.py
> +                return web.json_response(dict(message='Pinned to parent PID: ' + str(matches[0]), multiple_links=False))
Changed accordingly

2021-03-08 16:01 UTC, garunagiri commented on app/gameboard_api.py
> +        return None
Yeah I was surprised that the method doesn't exist elsewhere too, but I guess there's not too many places where we're concerned with the contents of the facts

2021-03-08 16:02 UTC, garunagiri commented on static/js/gameboard.js
> +    function updatedPin(data) {
That was a big function, I moved it out

2021-03-08 16:30 UTC, clenk approved these changes
Pending any changes to https://github.com/mitre/response/pull/66 that influence this one.

2021-03-09 18:39 UTC, merged