VIRTS-1080: Gameboard Blue Visualization
mitre/gameboard pull request #5
Opened 2020-04-17 19:57 UTC by mchan143

- Links aligned by PID
- Scoreboard cleaned up, operation status moved next to operation select
- Red links are hidden for Access.BLUE, blue links are hidden for Access.RED
- Modal cleaned up

2020-04-20 14:01 UTC, wbooth commented on static/js/gameboard.js
> +//let refresher = setInterval(refresh, 10000);
drop dead code

2020-04-20 14:01 UTC, wbooth commented on static/js/gameboard.js
> +//                getSuggestedQueries(fact);  // get suggested queries based on the passed in fact
drop dead code

2020-04-20 14:02 UTC, wbooth commented on static/js/gameboard.js
> +function getSuggestedQueries(fact) {
drop for now, put in followup

2020-05-01 16:29 UTC, privateducky commented
@wbooth how close are we to getting some functionality out there for game board?

2020-05-04 12:46 UTC, wbooth approved these changes

2020-05-04 13:28 UTC, privateducky commented on app/gameboard_api.py
> +            if link.pid in exchanges.keys():
lot of duplicate code in this block. can we condense?

2020-05-04 19:28 UTC, privateducky commented on app/gameboard_api.py
> +        response = dict(access="blue" if self.Access.BLUE in access else "red",
use single quotes

2020-05-05 15:00 UTC, wbooth commented on static/js/gameboard.js
> +        let spacing = '&nbsp;&nbsp;-&nbsp;&nbsp;';
if this isn't used we can drop it

2020-05-05 15:01 UTC, wbooth commented on static/js/gameboard.js
> +        for (let i=0; i<exchange['red'].length; i++){
if using I on 193 use a different var here for clarity

2020-05-05 15:02 UTC, wbooth commented on static/js/gameboard.js
> +        pid = exchanges[i][0]
use let to declare the variable here

2020-05-05 15:02 UTC, wbooth commented on static/js/gameboard.js
> +    let pid = 0;
if pid is not being used here drop let's drop it

2020-05-05 15:02 UTC, wbooth commented on static/js/gameboard.js
> +        for (let i=0; i<exchange['blue'].length; i++){
can we move these to functions since it's duplicated?

2020-05-05 15:07 UTC, wbooth requested changes
Code is working and provides a good improvement over the existing code. Can you take a second look to reorganize and clean up code. Looking specifically at duplicated sections (where you are doing the same for red and blue) and breaking up large functions that are doing 2 or 3 different things.

2020-05-06 23:35 UTC, wbooth approved these changes

2020-05-11 13:25 UTC, merged